In [2]:
!pip install syft

     |████████████████████████████████| 256kB 5.2MB/s 
     |████████████████████████████████| 81kB 30.5MB/s 
     |████████████████████████████████| 460kB 46.7MB/s 
     |████████████████████████████████| 389kB 47.9MB/s 
     |████████████████████████████████| 256kB 29.8MB/s 
     |████████████████████████████████| 1.4MB 39.1MB/s 
     |████████████████████████████████| 204kB 52.6MB/s 
     |████████████████████████████████| 51kB 22.1MB/s 
     |████████████████████████████████| 266kB 48.2MB/s 
     |████████████████████████████████| 122kB 47.7MB/s 
  Created wheel for zstd: filename=zstd-1.4.1.0-cp36-cp36m-linux_x86_64.whl size=1067073 sha256=e2f9a51eadf774336a820709aefde2aec1fc698469881b3011b959aa81a3d474
  Stored in directory: /root/.cache/pip/wheels/66/3f/ee/ac08c81af7c1b24a80c746df669ea3cb37542d27877d66ccf4
  Created wheel for pyyaml: filename=PyYAML-5.1.2-cp36-cp36m-linux_x86_64.whl size=44105 sha256=cb7e1961fc27bad794c2fe60ffff172872bfb334bfb7cd1de34cb07d41aae738
  Stored in di

In [3]:
import syft as sy
import torch as th
hook = sy.TorchHook(th)
from torch import nn, optim

W0813 05:57:32.324902 140408131975040 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0813 05:57:32.340172 140408131975040 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [7]:
bob = sy.VirtualWorker(hook, id="bob").add_worker(sy.local_worker)
alice = sy.VirtualWorker(hook, id="alice").add_worker(sy.local_worker)
secure_worker = sy.VirtualWorker(hook, id="secure_worker").add_worker(sy.local_worker)

W0813 06:04:07.798812 140408131975040 base.py:646] Worker me already exists. Replacing old worker which could cause                     unexpected behavior
W0813 06:04:07.803134 140408131975040 base.py:646] Worker me already exists. Replacing old worker which could cause                     unexpected behavior
W0813 06:04:07.808104 140408131975040 base.py:646] Worker me already exists. Replacing old worker which could cause                     unexpected behavior


In [0]:
x = th.tensor([1,2,3,4])
y = th.tensor([2,-1,1,0])

In [0]:
x = x.share(bob, alice, crypto_provider=secure_worker)

In [0]:
y = y.share(bob, alice, crypto_provider=secure_worker)

In [11]:
z = x - y
z.get()

tensor([-1,  3,  2,  4])

In [12]:
z = x + y
z.get()

tensor([3, 1, 4, 4])

In [13]:
z = x > y
z.get()

tensor([0, 1, 1, 1])

In [14]:
z = x < y
z.get()

tensor([1, 0, 0, 0])

In [15]:
z = x == y
z.get()

tensor([0, 0, 0, 0])

In [0]:
x = th.tensor([1,2,3,4])
y = th.tensor([2,-1,1,0])

x = x.fix_precision().share(bob, alice, crypto_provider=secure_worker)
y = y.fix_precision().share(bob, alice, crypto_provider=secure_worker)

In [17]:
z = x + y
z.get()

(Wrapper)>FixedPrecisionTensor>tensor([3000, 1000, 4000, 4000])

In [18]:
z = x - y
z.get()

(Wrapper)>FixedPrecisionTensor>tensor([-1000,  3000,  2000,  4000])

In [20]:
z = x * y
z.get().float_precision()

tensor([ 2., -2.,  3.,  0.])

In [21]:
z = x == y
z.get().float_precision()

tensor([0., 0., 0., 0.])

In [25]:
x[0:3].get().float_precision()

tensor([1., 2., 3.])