In [210]:
!pip install syft

In [0]:
import string
import torch as th

In [0]:

char2int = {}
index2char = {}

In [0]:

x = ' ' + string.ascii_lowercase + '0123456789' + string.punctuation

In [214]:

for i, char in enumerate(x):
  char2int[char] = i
  index2char[i] = char

print(char2int)
print(index2char)
 

{' ': 0, 'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26, '0': 27, '1': 28, '2': 29, '3': 30, '4': 31, '5': 32, '6': 33, '7': 34, '8': 35, '9': 36, '!': 37, '"': 38, '#': 39, '$': 40, '%': 41, '&': 42, "'": 43, '(': 44, ')': 45, '*': 46, '+': 47, ',': 48, '-': 49, '.': 50, '/': 51, ':': 52, ';': 53, '<': 54, '=': 55, '>': 56, '?': 57, '@': 58, '[': 59, '\\': 60, ']': 61, '^': 62, '_': 63, '`': 64, '{': 65, '|': 66, '}': 67, '~': 68}
{0: ' ', 1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 27: '0', 28: '1', 29: '2', 30: '3', 31: '4', 32: '5', 33: '6', 34: '7', 35: '8', 36: '9', 37: '!', 38: '"', 39: '#', 40: '$', 41: '%', 42: '&', 43: "'", 

In [0]:
str_input = 'Hello'
max_length = 8

In [0]:
def string2values(str_input, max_length=8):
  str_input = str_input[:max_length].lower()
  if (len(str_input) < max_length):
    str_input = str_input + "." * (max_length - len(str_input))

  values  = list()
  for char in str_input:
    values.append(char2int[char])
  return th.tensor(values).long()

def value2String(input_values):
  s = ""
  for values in input_values:
    s += index2char[int(values)]
  return s
    

In [217]:
string2values('sandeep')

tensor([19,  1, 14,  4,  5,  5, 16, 50])

In [0]:
def one_hot(index, length):
  vect = th.zeros(length).long()
  vect[index] = 1
  return vect

In [0]:








def string2one_hot(str_input, max_length=8):
  str_input = str_input[:max_length].lower()
  if (len(str_input) < max_length):
    str_input = str_input + "." * (max_length - len(str_input))
  char_vector = list()
  for char in str_input:
    char_v = one_hot(char2int[char], len(index2char)).unsqueeze(0)
    char_vector.append(char_v)
  return th.cat(char_vector, dim=0)
    

In [220]:
matrix = string2one_hot("Hello")
#matrix.shape
matrix

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 

In [0]:



string_a = string2one_hot("abcdef")
string_b = string2one_hot("sandeep")

In [222]:


(string_a * string_b).sum() #shows letters in common

tensor(3)

In [223]:

(string_a * string_b).sum(1) #for perfect matching

tensor([0, 0, 0, 1, 1, 0, 0, 1])

In [0]:

def string_compare(str_a, str_b):
  vect = (string_a * string_b).sum(1)
  x = vect[0]
  for i in range(vect.shape[0] - 1):
    x = x + vect[i + 1]
  key_match = x
  return key_match

In [225]:
query("key1")

'                      f                                              '

In [0]:
class EncryptedDatabase():
  def __init__(self, *owners, max_key_len=8, max_val_len=0):
    self.max_key_len = 8
    self.max_val_len = 8
    
    
    self.keys = list()
    self.values = list()
    self.owners = owners
#     self.keys.append(string2one_hot("key1"))
#     self.values.append(string2one_hot("value1"))
  def add_entry(self, key, value):
    key = string2one_hot(key)
    key = key.share(*self.owners)
    self.keys.append(string2one_hot(key))
    
    value = string2one_hot(value)
    value = value.share(*self.owners)
    self.values.append(string2one_hot(value))
  def query(self, str):
    Query_str = "key2"
    query_matrix = string2one_hot(Query_str)
    
    query_matrix = query_matrix.share(*self.owners)
    

    key_matches = list()
    for key in self.keys:
      key_match = string_compare(key, query_matrix)
      key_matches.append(key_match)
    key_matches

    result = self.values[0] * key_matches[0]
    # value2String([[2,1])
    for i in range(len(self.values) -1 ):
      result += self.values[i+1] + key_matches[i+1]
    # value2String(result)
  
    return value2String(result[0]).replace(".","")

    
 

In [234]:
import syft as sy
hook = sy.TorchHook(th)
bob = sy.VirtualWorker(hook, id="bob").add_worker(sy.local_worker)
alice = sy.VirtualWorker(hook, id="alice").add_worker(sy.local_worker)
secure_worker = sy.VirtualWorker(hook, id="secure_worker").add_worker(sy.local_worker)

W0813 08:47:00.797959 139784771725184 base.py:646] Worker me already exists. Replacing old worker which could cause                     unexpected behavior
W0813 08:47:00.799703 139784771725184 base.py:646] Worker me already exists. Replacing old worker which could cause                     unexpected behavior
W0813 08:47:00.800768 139784771725184 base.py:646] Worker me already exists. Replacing old worker which could cause                     unexpected behavior


In [0]:

db = EncryptedDatabase(bob, alice, secure_worker)
db.add_entry("key1", "value1")
db.add_entry("key2", "value2")
db.add_entry("key3", "value3")

In [233]:
db.query("key1")

'ffffffffffffffffffffffkffffffffffffffffffffffffffffffffffffffffffffff'

have some range mismatch, fixes needed

In [228]:

index2char

{0: ' ',
 1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 27: '0',
 28: '1',
 29: '2',
 30: '3',
 31: '4',
 32: '5',
 33: '6',
 34: '7',
 35: '8',
 36: '9',
 37: '!',
 38: '"',
 39: '#',
 40: '$',
 41: '%',
 42: '&',
 43: "'",
 44: '(',
 45: ')',
 46: '*',
 47: '+',
 48: ',',
 49: '-',
 50: '.',
 51: '/',
 52: ':',
 53: ';',
 54: '<',
 55: '=',
 56: '>',
 57: '?',
 58: '@',
 59: '[',
 60: '\\',
 61: ']',
 62: '^',
 63: '_',
 64: '`',
 65: '{',
 66: '|',
 67: '}',
 68: '~'}