In [1]:
# create the initial database
#create all parallel database

In [2]:
import torch

In [3]:
num_entries = 5000
db = torch.rand(num_entries) > 0.5
db

tensor([1, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8)

In [4]:
db.shape

torch.Size([5000])

In [5]:
db.size()

torch.Size([5000])

In [6]:
db[0:5]

tensor([1, 0, 0, 1, 0], dtype=torch.uint8)

In [7]:
remove_index = 2

In [8]:
def get_parallel_db(db, remove_index):
    return torch.cat((db[0:remove_index], db[remove_index+1:]))

In [9]:
get_parallel_db(db, 0)[0:5]

tensor([0, 0, 1, 0, 0], dtype=torch.uint8)

In [10]:
get_parallel_db(db, 0).shape #removed 1st index

torch.Size([4999])

In [11]:
def get_parallel_dbs(db):
    parallel_db = list() 
    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_db.append(pdb)
    return parallel_db

In [12]:
len(db)

5000

In [13]:
pdb

Automatic pdb calling has been turned ON


In [14]:
def create_db_and_parallel(num_entries):
    dbs = torch.rand(num_entries) > 0.5
    pdbs = get_parallel_dbs(dbs)
    return dbs, pdbs
    

In [15]:
dbs, pdbs = create_db_and_parallel(20)

In [16]:
db

tensor([1, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8)

In [17]:
def query(db):
    return db.sum()
    

In [18]:
print(query(db))

tensor(2478)


In [19]:
# Creating the database

db, pdbs =  create_db_and_parallel(5000)

In [20]:
db

tensor([1, 0, 0,  ..., 1, 1, 1], dtype=torch.uint8)

In [21]:
def query(db):
    return db.sum()

In [22]:
full_db_res = query(db)  ## 13 1's present in database

In [23]:
query(pdbs[2])

tensor(2464)

In [ ]:
max_distance = 0
for pdb in pdbs:
    pdb_res = query(pdb)
    db_dist = torch.abs(pdb_res - full_db_res)
    
    if db_dist > max_distance:
        max_distance = db_dist 

In [ ]:
max_diatance